/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_givimad_libfvadjni_VoiceActivityDetector */

#ifndef _Included_io_github_givimad_libfvadjni_VoiceActivityDetector
#define _Included_io_github_givimad_libfvadjni_VoiceActivityDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadNew
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadNew
  (JNIEnv *, jclass);

/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadReset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadReset
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadSetMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadSetMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadSetSampleRate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadSetSampleRate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadProcess
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadProcess
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     io_github_givimad_libfvadjni_VoiceActivityDetector
 * Method:    fvadFree
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_libfvadjni_VoiceActivityDetector_fvadFree
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
